### PR TITLE
Spring Cleaning URL Change

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by imbstack** [comment]
This looks pretty good. I have some potential additional action items, what do you two think?

1. Some sort of alerting for 403/500/etc spikes from our services
2. Doing an audit of our services to check and see if we have potentially overly specific validation for external urls that can change without us knowing

Do either of those make sense? They're sorta larger projects so maybe aren't good action items here.

**Comment by djmitche** [comment]
It doesn't look like Heroku allows alerting on specific HTTP codes, so we'd have to do that in papertrail.  Which actually makes it a little easier, I think? (we could do it across all services)

**Comment by djmitche** [comment]
Regarding the second point, I think spotting this sort of thing is pretty difficult -- enough that doing so over all services is a long time commitment anyway.  I'll add the first point.

**Comment by djmitche** [comment]
I think we're now focused on #7 and can call this one fully written.

**Pull request merged**
