### PR TITLE
Spot Requests Pending Forever

### PR DESCRIPTION
**Pull request by djmitche**
Posting this while the incident is ongoing, for visibility and in case others want to add information.

### CODE REVIEW

**Comment by jhford** [comment]
i'm way to tired to format this into the PR, but a cople things to note.  We started melting down the provisioner/spot api when recovering from the windows issue, which led to a bunch of weird and new errors in the ec2-manager.  that required a couple diagnostics patches which included a bit of new code which caused a weird self-fixing memory leak that operated on a 10 minute cycle.  Memory went from 200mb constant to 2gb rapid max, then would have a couple 500s, then back to normal memory.  I split out the ec2-manager into smaller dynos and found the cause and removed the offending code.

**Comment by jhford** [comment]
oh and some action items:

1. reconsider work involving ec2 resources when ec2 is not working
2. only delete images which are not in use and haven't been used in a while
3. all image auto-purging should use time to decide if an image is to be deleted, not the count of previous images.

**Comment by djmitche** [comment]
This is a copy/paste of the etherpad at the end of today's meeting.

@indygreg @grenade please also share any feedback (you're not in the repo so I can't flag for review)

**Review by walac — APPROVED** [review]

**Review by imbstack — APPROVED** [review]

**Comment by djmitche** [comment]
I'll merge, I think interest in this set of issues has flagged.  If there's more feedback we can make more changes.

**Pull request merged**
