### PR TITLE
Auth Sentry Crash

### PR DESCRIPTION
**Pull request by djmitche**
I made up the action items; please let me know what you think.

### CODE REVIEW

**Comment by imbstack** [comment]
Good so far but we'll figure out root cause first before landing I assume?

**Comment by djmitche** [comment]
We appear to not be out of the woods, yeah.

**Review by imbstack — APPROVED** [review]
Maybe for action items we can mention avoiding auth-ing in cases where there is no need to auth, but that's only sorta-kinda related.

**Comment by djmitche** [comment]
I think the "important" API calls would still have failed in that condition..

**Comment by jonasfj** [comment]
Looking at:

I don't get impression that the [app crashed H10](https://devcenter.heroku.com/articles/error-codes#h10-app-crashed)

Instead looking at:


It seems more like we were hit with too many requests... looking at tc-lib-monitor it's looks like it'll log the failure to report to sentry, but not crash the app of an error... So possible problems might be:

 * We had an error where crashing the app would have been the right thing to do (and we didn't)
 * tc-lib-monitor in other apps kept pinging tc-auth for creds, and a temporary outage in sentry caused that to take time (and fail), leading to overload and outage

I think we could mitigate the second issue here, but setting expiration for state that is failure to fetch sentry credentials to something like 30s... that would do a lot.. See:
 https://github.com/taskcluster/taskcluster-lib-monitor/blob/38ccb9ba5d8a72231a4362e8b1e511e65b9239bb/src/monitor.js#L35
(ie. tweak expires in this line ^)

----
Note: i think multiple things went wrong to make this so bad... If we had fewer things reporting to sentry all the time, this wouldn't have been so bad either. So this isn't just one error...

**Review by jonasfj — APPROVED** [review]

**Comment by djmitche** [comment]
Here's a zoom of the monitoring for the critical time.  You're right that there are no H10's..

screenshot from 2018-01-08 13-29-52

Does a single express node have a limit in the number of simultaneous connections it will accept?  Or perhaps this was just so bad that 1000's of requests piled up, hung.  But Heroku won't hold a connection open and idle for more than 30s (we know that from the queue), so that would have to be 5 (dynos) x 1000's of requests in 30s -- it's hard to see how even in a failure situation we would have had that number of requests for Sentry tokens.

**Comment by jonasfj** [comment]
> Does a single express node have a limit in the number of simultaneous connections it will accept?

I think so... if not heroku probably has a limit...

Regardless, it could run us out of CPU or network bandwidth... if the thing was retrying a lot...

**Comment by edmorley** [comment]
Note the process/thread limit might play a role here, depending on what dyno size you're using:
https://devcenter.heroku.com/articles/limits#processes-threads

Also if tc-auth is using the legacy SSL feature, then it's using a dedicated AWS ELB that takes a while to scale (unlike the shared infra).

Other than that, I'd check out:
https://devcenter.heroku.com/articles/http-routing

Also - would it be possible to modify the Heroku alerts settings for the tc-auth app, so it doesn't email all Heroku admins? (eg uncheck the unhelpfully named "email all app members", and add a manual email mailing list/alias)

**Comment by djmitche** [comment]
> Also - would it be possible to modify the Heroku alerts settings for the tc-auth app, so it doesn't email all Heroku admins? (eg uncheck the unhelpfully named "email all app members", and add a manual email mailing list/alias)

Done

**Comment by djmitche** [comment]
I think I've left out some possible causes, so please suggest..

**Review by imbstack — APPROVED** [review]

**Review by jonasfj — APPROVED** [review]

**Pull request merged**
